import java.util.Scanner;

public class ConsoleUI {

    // Just a decorative bar :)
    public final static String bar = "+=+=+=+=+=+=+=+=+=+=+=+=+";

    /**
     * Displays the main menu and instructions to the user
     * Scanner object for waiting user input
     * Note: This method is separated to maintain clean separation from business logic
     */
    public static void showMenu(Scanner scanner) {
        System.out.printf("""
            %s
             The Password Generator
            %s
            Generate a secure, multi-word password.
            1. Choose how many words your password will have.
            2. Get a randomly generated password.
            3. Each word is generated by rolling five dice, using a list of 7,776 words.
            4. Memorize it by creating a short story for each word.
            5. Use your new password to stay safe online.

            Press Enter to continue...
            """, bar, bar);

        scanner.nextLine(); // Wait for user to press Enter to continue

        System.out.print("""
                Tip: For better security, choose more than three words.
                Let's get started!
                Press Enter to continue...
                """);
        scanner.nextLine(); // Wait one more time
    }

    /**
     * Reads user input(numWords) for the number of words to generate in the password
     * Positive integer representing the number of words
     * Loops until a valid positive integer is entered
     */
    public static int readUserInput(Scanner scanner) {
        while (true) {
            System.out.println("How many words would you like in your password? ");
            try {
                int numWords = Integer.parseInt(scanner.nextLine().trim());
                if (numWords > 0) {
                    System.out.println("Generating password...");
                    return numWords;
                }
                // Input was not positive
                System.out.println("Invalid input. Please enter a positive number.");
            } catch (NumberFormatException e) {
                // Input was not an integer
                System.out.println("Invalid input. Please enter a integer number.");
            }
        }
    }

    /**
     * Pauses execution for a given number of milliseconds.
     * num Number of milliseconds to sleep
     */
    public static void sleep(int num) {
        try {
            Thread.sleep(num);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt(); // Restore interrupted status
        }
    }
}
